### ISSUE TITLE
Use of the OAS term

### ISSUE THREAD

**Issue by letzya** [TykTechnologies/exp#8]
With regards to fields, docs, and files related to the Tyk OAS API definition, can we please make sure it's clear that it's an API definition? Can we avoid using just the term `oas`? 
Reason - It's confusing with Tyk's OpenAPI docs that document Tyk APIs. In this file https://github.com/TykTechnologies/exp/blob/89e3c0d67ad7e2f2bfd19cb6ae212ce8c982ca50/pkg/model/oas/oas.json#L1
 you document the fields of the API definition, which are not part of the o0penapi spec at all, but part of Tyk proprietary API definition. It's confusing for visitors of the repo, that are not familiar and don't have the context. Even I double-checked it to make sure I got it correctly (although I'm part of the Tyk OAS API Def project).  Thanks

**Comment by titpetric** [comment]
does not apply to this repo
